# ğŸ‘ Thanks: https://zenn.dev/nikaera/articles/vercel-github-actions

# catnose.me/timelineã«ç§»è¡Œã—ãŸã®ã§actionsã‚’åœæ­¢

# name: deploy on vercel

# on:
#   push:
#     branches:
#       - main
#   schedule:
#     - cron: '0 2 * * *'
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.inputs.ref }}
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - uses: amondnet/vercel-action@v20
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }}
#           vercel-args: '--prod'
#           vercel-org-id: ${{ secrets.ORG_ID}}
#           vercel-project-id: ${{ secrets.PROJECT_ID}}
#           working-directory: ./
